config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "rentals#index"

  resources :bikes do
    member do
      post :deactivate
    end
  end

  resources :employees do
    member do
      post :deactivate
    end
  end

  resources :rentals do
    member do
      post :cancel
    end

    collection do
      get :export
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  has_many :rentals

  scope :active, -> { where(active: true) }

  validates :name, presence: true, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :rentals

  scope :active, -> { where(active: true) }

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
    uniqueness: { case_sensitive: false, if: :email_changed? },
    format: { with: URI::MailTo::EMAIL_REGEXP }

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :employee
  belongs_to :bike

  scope :active, -> { where(canceled: false) }
  scope :by_date_range, ->(start_date, end_date) { where(start_time: start_date.beginning_of_day..end_date.end_of_day) }

  validates :start_time, presence: true
  validates :end_time, presence: true
  validate :end_time_after_start_time
  validate :bike_availability

  private

  def end_time_after_start_time
    return if end_time.blank? || start_time.blank?
    errors.add(:end_time, I18n.t("activerecord.errors.messages.cant_be_before")) if end_time <= start_time
  end

  def bike_availability
    return if bike_id.blank? || start_time.blank? || end_time.blank? || canceled?

    overlapping_rentals = Rental.active.where(bike_id: bike_id)
                                 .where("start_time < ? AND end_time > ?", end_time, start_time)

    if overlapping_rentals.exists?
      errors.add(:bike, I18n.t("activerecord.errors.messages.not_available"))
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: %i[edit update deactivate]

  def index
    @bikes = Bike.active
  end

  def new
    @bike = Bike.new
  end

  def edit
  end

  def create
    @bike = Bike.new(bike_params)

    if @bike.save
      redirect_to bikes_path, notice: t("bikes.notices.successfully_created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @bike.update(bike_params)
      redirect_to bikes_path, notice: t("bikes.notices.successfully_updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def deactivate
    if @bike.update(active: false)
      redirect_to bikes_path, notice: t("bikes.notices.successfully_deactivated")
    else
      redirect_to bikes_path, alert: t("bikes.notices.unsuccessfully_deactivated")
    end
  end

  private

  def set_bike
    @bike ||= Bike.find(params[:id])
  end

  def bike_params
    params.require(:bike).permit(:name)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[edit update deactivate]

  def index
    @employees = Employee.active
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to employees_path, notice: t("employees.notices.successfully_created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @employee.update(employee_params)
      redirect_to employees_path, notice: t("employees.notices.successfully_updated")
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def deactivate
    if @employee.update(active: false)
      redirect_to employees_path, notice: t("employees.notices.successfully_deactivated")
    else
      redirect_to employees_path, alert:  t("employees.notices.unsuccessfully_deactivated")
    end
  end

  private

  def set_employee
    @employee ||= Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :email)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_employees_and_bikes, only: [ :new, :create ]

  def index
    @rentals = Rental.includes(:employee, :bike).active
  end

  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.new(rental_params)
    if @rental.save
      redirect_to rentals_path, notice: t("rentals.notices.successfully_created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  def cancel
    rental = Rental.find(params[:id])

    if rental.update(canceled: true)
      redirect_to rentals_path, notice: t("rentals.notices.successfully_canceled")
    else
      redirect_to rentals_path, alert: t("rentals.notices.unsuccessfully_canceled")
    end
  end

  def export
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    export_service = RentalExportService.new(start_date, end_date)

    data = export_service.generate_csv

    respond_to do |format|
      format.csv { send_data data, filename: t("export.file_name", start_date: start_date, end_date: end_date) }
    end
  end

  private

  def set_employees_and_bikes
    @employees ||= Employee.active
    @bikes ||= Bike.active
  end

  def rental_params
    params.require(:rental).permit(:employee_id, :bike_id, :start_time, :end_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_form.html.haml
.form-container
  = form_with(model: bike) do |form|
    = render 'layouts/error_messages', object: bike

    .form-group
      = form.label :name, class: 'form-label'
      = form.text_field :name, class: 'form-field'

    .actions
      = form.submit submit_text, class: 'btn btn-primary'

  %div
    = link_to t('common.back_to_list'), bikes_path, class: 'btn btn-secondary'

app/views/bikes/edit.html.haml
%h1= t('bikes.edit')

= render "form", bike: @bike, submit_text: t('bikes.edit')

app/views/bikes/index.html.haml
%h1= t('bikes.list')

.table-container
  %table
    %thead
      %tr
        %th= t('bikes.name')
        %th= t('common.actions')
    %tbody
      - @bikes.each do |bike|
        %tr
          %td= bike.name
          %td
            = link_to t('common.edit'), edit_bike_path(bike)
            = link_to t('common.deactivate'),
                deactivate_bike_path(bike),
                data: { turbo_method: :post, turbo_confirm: t('bikes.deactivate_confirmation') }

  = link_to t('bikes.create_new'), new_bike_path, class: 'btn btn-primary'

app/views/bikes/new.html.haml
%h1= t('bikes.new')

= render "form", bike: @bike, submit_text: t('bikes.create_new')

app/views/employees/_form.html.haml
.form-container
  = form_with(model: @employee, local: true, html: { novalidate: true }) do |form|
    = render 'layouts/error_messages', object: employee

    .form-group
      = form.label :first_name, class: 'form-label'
      = form.text_field :first_name, class: 'form-field'

    .form-group
      = form.label :last_name, class: 'form-label'
      = form.text_field :last_name, class: 'form-field'

    .form-group
      = form.label :email, class: 'form-label'
      = form.email_field :email, class: 'form-field'

    .actions
      = form.submit submit_text, class: 'btn btn-primary'

  %div
    = link_to t('common.back_to_list'), employees_path, class: 'btn btn-secondary'

app/views/employees/edit.html.haml
%h1= t('employees.edit')

= render "form", employee: @employee, submit_text: t('employees.edit')

app/views/employees/index.html.haml
%h1= t('employees.list')

.table-container
  %table
    %thead
      %tr
        %th= t('employees.name')
        %th= t('employees.email')
        %th= t('common.actions')
    %tbody
      - @employees.each do |employee|
        %tr
          %td= employee.full_name
          %td= employee.email
          %td
            = link_to t('common.edit'), edit_employee_path(employee)
            = link_to t('common.deactivate'),
                deactivate_employee_path(employee),
                data: { turbo_method: :post, turbo_confirm: t('employees.deactivate_confirmation') }

  = link_to t('employees.create_new'), new_employee_path, class: 'btn btn-primary'

app/views/employees/new.html.haml
%h1= t('employees.new')

= render 'form', employee: @employee, submit_text: t('employees.create_new')

app/views/layouts/_error_messages.html.haml
- if object.errors.any?
  .error-message
    %h2= t('common.could_not_create')
    %ul
      - object.errors.full_messages.each do |message|
        %li= message

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, message|
  .flash{ class: key }
    = message

app/views/layouts/_navbar.html.haml
%nav
  %ul
    %li= link_to t('navbar.bikes'), bikes_path
    %li= link_to t('navbar.employees'), employees_path
    %li= link_to t('navbar.rentals'), rentals_path

app/views/layouts/application.html.haml
!!!  # This is equivalent to <!DOCTYPE html>
%html
  %head
    %title= content_for(:title) || t('common.title')
    %meta{name: "viewport", content: "width=device-width,initial-scale=1"}
    %meta{name: "apple-mobile-web-app-capable", content: "yes"}
    = csrf_meta_tags
    = csp_meta_tag

    = yield :head

    %link{rel: "manifest", href: "/manifest.json"}
    %link{rel: "icon", href: "/icon.png", type: "image/png"}
    %link{rel: "icon", href: "/icon.svg", type: "image/svg+xml"}
    %link{rel: "apple-touch-icon", href: "/icon.png"}
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  %body
    = render 'layouts/navbar'
    = render 'layouts/flash_messages'

    = yield

app/views/rentals/_form.html.haml
.form-container
  = form_with(model: rental, local: true) do |form|
    = render 'layouts/error_messages', object: rental

    .inline-group
      .form-group
        = form.label :employee_id, t('rentals.employee'), class: 'form-label'
        = form.collection_select :employee_id, employees, :id, :full_name, 
            { prompt: t('rentals.choose_employee') }, 
            { class: 'form-field select-field' }

      .form-group
        = form.label :bike_id, t('rentals.bike'), class: 'form-label'
        = form.collection_select :bike_id, bikes, :id, :name, 
            { prompt: t('rentals.choose_bike') }, 
            { class: 'form-field select-field' }

    .inline-group
      .form-group
        = form.label :start_time, class: 'form-label'
        = form.datetime_field :start_time, class: 'form-field date-field'

        = form.label :end_time, class: 'form-label'
        = form.datetime_field :end_time, class: 'form-field date-field'

    .actions
      = form.submit t('rentals.create_new'), class: 'btn btn-primary'

  %div
    = link_to t('common.back_to_list'), rentals_path, class: 'btn btn-secondary'

app/views/rentals/index.html.haml
%h1= t('rentals.list')

.table-container
  %table
    %thead
      %tr
        %th= t('rentals.start_time')
        %th= t('rentals.end_time')
        %th= t('rentals.bike_name')
        %th= t('rentals.employee_name')
        %th= t('common.actions')
    %tbody
      - @rentals.each do |rental|
        %tr
          %td= rental.start_time
          %td= rental.end_time
          %td= rental.bike.name
          %td= rental.employee.full_name
          %td
            = link_to t('common.cancel'),
                cancel_rental_path(rental),
                data: { turbo_method: :post, turbo_confirm: t('rentals.cancel_confirmation') }

  = link_to t('rentals.new'), new_rental_path, class: 'btn btn-primary'

  .export-container
    %h2= t('export.export_list')

    = form_with url: export_rentals_path(format: :csv), method: :get, local: true do |form|
      .inline-group
        .form-group
          = form.label :start_date, t('export.dates'), class: 'form-label'
          = form.date_field :start_date, class: 'form-field'
          = "-"
          = form.date_field :end_date, class: 'form-field'
      = form.submit t('common.export'), class: 'btn btn-primary'

app/views/rentals/new.html.haml
%h1= t('rentals.new')

= render "form", rental: @rental, employees: @employees, bikes: @bikes